# -*- coding: utf-8 -*-
"""HashesAndPasswords_151253_152516.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RXi-rxDFM9mtAKWHBHo6Zdh_YVSq_Tly

Assignment 5 - Hashes and Passwords
Names: Adrian Dominic Danao, John Michael Benedict P. Lingad 
ID #s: 151253, 152516 
Email Addresses: adrian.danao@obf.ateneo.edu, john.lingad@obf.ateneo.edu
"""

import crypt, getpass

type_pass = getpass.getpass("Type a password: ")

#manually typed from command sudo cat /etc/shadow
#coming <user>:{}${}${}:... format 
#dollar signs are used as separators and there are 3 fields
#field 1 = hashing used, if it's 1, it uses MD5 hashing
#field 2 = salt used to generate the hash, 8 char
#field 3 = hashed password generated along with the salt, 22 char

#password for both root and user is testpass

root_pass = "$1$6vfq7/zx$T65fxRhHGVhpHf/qIOmJJ/"
user_pass = "$1$g3m/LnwT$IhTWIEOsBvs8XzE7NSPH.."

check_root_pass = crypt.crypt(type_pass, root_pass)
if(check_root_pass == root_pass): print("The password you typed matched the password for root!")
else: print("Passwords don't match for root!")

check_user_pass = crypt.crypt(type_pass, user_pass)
if(check_user_pass == user_pass): print("The password you typed matched the password for a user!")
else: print("Passwords don't match for user!")

