# -*- coding: utf-8 -*-
"""152516-SSHCrawler2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12pXj71NjzhnjtpdoHJH9IvKhsfTzTdYJ

This is it... My Python Jupyter Assignment
John Michael Benedict P. Lingad
152516
john.lingad@obf.ateneo.edu
"""

import paramiko
import getpass

hostname = raw_input("Please enter hostname: ")
port = raw_input("Please enter port: ")
username = raw_input("Please enter username: ")
password = getpass.getpass("Please enter password: ")

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(hostname, port, username, password, allow_agent=False, look_for_keys=False)

stdin, stdout, stderr = client.exec_command("last")
output = stdout.read()
print "\n" + output;