# -*- coding: utf-8 -*-
"""152516-SSHCrawler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z3ar8HW64-IqDQogmKfCBfNXex0NRaEv
"""

# Assignment 1 - My Python Jupyter Assignment
# John Michael Benedict P. Lingad
# 152516
# john.lingad@obf.ateneo.edu

import paramiko
import getpass
import socket

username = raw_input("Please input username for SSH connection: ")
password = getpass.getpass("Please input password for SSH connection: ")

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(socket.gethostname(), 22, username, password, allow_agent=False, look_for_keys=False)

stdin, stdout, stderr = client.exec_command("cd /usr/bin && printf '\n \tPrinting files of /usr/bin sorted by name showing name and modification date \n' && ls -l | awk '{print $9, $6, $7, $8}' && printf '\n \tPrinting files from /usr/bin sorted by newest to oldest showing file name and modification date \n' && ls -lt | awk '{print $9, $6, $7, $8}'")
out = stdout.read()
print out